### ISSUE TITLE
(AOT) ScanProjectForSerializedTypes only returns 2 types and has asserts unity 2018.3.0f2

### ISSUE THREAD

**Issue by dizzy2003** [TeamSirenix/odin-serializer#10] opened 2018-12-29 03:31 UTC
Asserts 

[Assert] Assertion failed on expression: 'GetApplication().MayUpdate()'
UnityEditor.SceneManagement.EditorSceneManager:NewScene(NewSceneSetup, NewSceneMode)
AOTSupportScanner.ScanScenes()    C:/Sirenix/OdinSerializer/OdinSerializer/Unity Integration/AOTSupportScanner.cs:257

AOTSupportScanner.ScanBuildScenes()    C:/Sirenix/OdinSerializer/OdinSerializer/Unity Integration/AOTSupportScanner.cs:179

AOTSupportUtilities.ScanProjectForSerializedTypes()    C:/Sirenix/OdinSerializer/OdinSerializer/Unity Integration/AOTSupportUtilities.cs:48

OdinBuildAutomation.OnPreprocessBuild()    Assets/Plugins/Sirenix/Odin Serializer/OdinBuildAutomation.cs:74

OdinPreBuildAutomation.OnPreprocessBuild()    Assets/Plugins/Sirenix/Odin Serializer/OdinBuildAutomation.cs:116

GUIUtility.ProcessEvent()

And

[Assert] Assertion failed on expression: '!performAutorepaint || GetApplication().MayUpdate()'
UnityEditor.SceneManagement.EditorSceneManager:NewScene(NewSceneSetup, NewSceneMode)
AOTSupportScanner.ScanScenes()    C:/Sirenix/OdinSerializer/OdinSerializer/Unity Integration/AOTSupportScanner.cs:257

AOTSupportScanner.ScanBuildScenes()    C:/Sirenix/OdinSerializer/OdinSerializer/Unity Integration/AOTSupportScanner.cs:179

AOTSupportUtilities.ScanProjectForSerializedTypes()    C:/Sirenix/OdinSerializer/OdinSerializer/Unity Integration/AOTSupportUtilities.cs:48

OdinBuildAutomation.OnPreprocessBuild()    Assets/Plugins/Sirenix/Odin Serializer/OdinBuildAutomation.cs:74

OdinPreBuildAutomation.OnPreprocessBuild()    Assets/Plugins/Sirenix/Odin Serializer/OdinBuildAutomation.cs:116

GUIUtility.ProcessEvent()

Am trying to build for switch using il2cpp

two types that were output
OdinBuildAutomation types csDelaunay.Voronoi
OdinBuildAutomation types csDelaunay.Voronoi[]

Note running the build when it tries to deserialize a file it complains that Vector2 wasnt added as a type.

**Comment by Manuel-Meyer** [comment] 2019-03-04 12:50
Same Problem here!

**Comment by tomh4** [comment] 2019-05-13 22:29
Having the same issue, any help?

**Comment by TorVestergaard** [comment] 2019-05-13 22:40
Hmm, a lot of people seem to be getting this recently. Is this happening on the latest master commit, or on the latest release build (1.1.1.0)? If it's the release, can you try building from the latest master commit and see if it is fixed there? I have had it reported before and made some changes to attempt to handle it if it happens, but I have never managed to reproduce it locally at any time.

**Comment by tomh4** [comment] 2019-05-13 23:03
I am using a build from the latest master commit. It appears upon building (in my case for windows standalone ) on Unity 2018.3.11f1

**Comment by Manuel-Meyer** [comment] 2019-05-14 06:21
Switching to Unity 2019.1 solved the problem for me.

**Comment by tomh4** [comment] 2019-05-16 21:22
@TorVestergaard I recompiled from the latest commit but I am still experiencing the exact same issue

**Comment by TorVestergaard** [comment] 2019-05-16 22:17
@tomh4 If you look in the code, you'll see that we disable error logging and silently catch all exceptions that occur during the call that causes the error - which is a call we do need to make, ideally, since if it's not there, Unity starts complaining in other ways. I'm honestly not sure what else to do, here - I've exhausted all the options I am aware of that should be able to swallow the error silently :/

I've still not managed to replicate the issue myself. It's quite mysterious to me, but I've never seen it once, and no one has managed to send me a project that replicates, which makes it rather hard to attempt fixes - hence my method of just trying to swallow the error silently.

Has the error been reported to Unity by someone with a reliably replicating project? Perhaps that is the best course of attack. Or, of course, anyone can feel free to send me a replicating project at tor@sirenix.net - we've got to get lucky, some time.

**Comment by tomh4** [comment] 2019-05-17 14:10
Upgrading to 2019 is not an option though as we planned to use the serializer as part of an asset...

**Comment by ahmkam** [comment] 2019-06-20 20:44
still facing the same issue even after using the plugin from the fix branch. Been trying to make it work since past 5 years, any solution to this?

**Comment by TorVestergaard** [comment] 2019-06-21 10:35
Strange that changing the API compatibility level would make a difference. That's good to hear. Meanwhile, if you look at this pull request, it contains a fix and has figured out what was going wrong. The fix is merely very specific in that pull request, and I've been trying to figure out a more general one. https://github.com/TeamSirenix/odin-serializer/pull/20

**Comment by lazlo-bonin** [comment] 2019-10-07 17:40
Just ran into this as well for Bolt, but in my case, switching to .NET 4.x didn't make it go away.

I'm building with the latest version on Windows + IL2CPP.

The assertions are worrisome but seem harmless, but users have already started reporting them.

**Comment by TorVestergaard** [comment] 2019-11-04 12:33
Latest commit should have a fix for this. After a long time dilly-dallying over this issue and how to solve it 'correctly', I've decided to just rule that you're not allowed to be in a state of asset editing (begun with 'AssetDatabase.StartAssetEditing()') during an AOT scene scan, since being in that state is what is causing the issue. Not making a temporary new scene before restoring the scene setup comes with issues of its own, and will cause restoring the scene setup to fail occasionally with more serious exceptions.

To this effect, I've edited the provided OdinBuildAutomation.cs script to make sure that we never enter a state of asset editing, but instead do things the slightly slower but much safer and more reliable way of messing with stuff, and then calling AssetDatabase.Refresh().

The issue that makes this difficult, and why I've not really dealt conclusively with this before now (thanks for poking me, Lazlo), comes from the fact that AssetDatabase.Start/StopAssetEditing() is a stack, and there is no way to find out the depth of that stack. Therefore, there simply is no way (that I've discovered) to temporarily 'jump out' of asset editing, and then back in at the same level. We would have to make our own utility for keeping track of the asset editing depth, that everyone would have to use to start and stop asset editing mode, before this works. And that's just not a good solution.

So this is why I've not accepted that pull request in so long, and what I've ended up with as a 'solution'. Let's hope this resolves the issue definitively, and provides enough information for people googling for it to solve it themselves if they do run into it. (Don't be in asset editing mode when you run an AOT support scan!)

**Closed by TorVestergaard** 2019-11-04 12:33 UTC
